name: 🎉 Release Binary

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Dependencies
        run: sudo apt-get install git default-jdk
           

      - name: Setting up ProjectDiscovery tools
        run: |
          cd /usr/local
          wget https://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar -zxvf apache-maven-3.6.3-bin.tar.gz
          export MAVEN_HOME=/usr/local/apache-maven-3.6.3
          export PATH=$MAVEN_HOME/bin:$PATH
          git clone https://github.com/karthikuj/cve-2022-42889-text4shell-docker.git
          cd cve-2022-42889-text4shell-docker
          mvn clean install
        shell: bash
          
      - name: Push changes
        uses: actions/upload-artifact@v2
        with:
          name: 1
          path: ./*.jar
